#ifndef __LIBC_LINUX_X86_64_BITS_SYSCALL_TABLE_H__
#define __LIBC_LINUX_X86_64_BITS_SYSCALL_TABLE_H__

#define __SYS_read                    0
#define __SYS_write                   1
#define __SYS_open                    2
#define __SYS_close                   3
#define __SYS_stat                    4
#define __SYS_fstat                   5
#define __SYS_lstat                   6
#define __SYS_poll                    7
#define __SYS_lseek                   8
#define __SYS_mmap                    9
#define __SYS_mprotect               10
#define __SYS_munmap                 11
#define __SYS_brk                    12
#define __SYS_rt_sigaction           13
#define __SYS_rt_sigprocmask         14
#define __SYS_rt_sigreturn           15
#define __SYS_ioctl                  16
#define __SYS_pread64                17
#define __SYS_pwrite64               18
#define __SYS_readv                  19
#define __SYS_writev                 20
#define __SYS_access                 21
#define __SYS_pipe                   22
#define __SYS_select                 23
#define __SYS_sched_yield            24
#define __SYS_mremap                 25
#define __SYS_msync                  26
#define __SYS_mincore                27
#define __SYS_madvise                28
#define __SYS_shmget                 29
#define __SYS_shmat                  30
#define __SYS_shmctl                 31
#define __SYS_dup                    32
#define __SYS_dup2                   33
#define __SYS_pause                  34
#define __SYS_nanosleep              35
#define __SYS_getitimer              36
#define __SYS_alarm                  37
#define __SYS_setitimer              38
#define __SYS_getpid                 39
#define __SYS_sendfile               40
#define __SYS_socket                 41
#define __SYS_connect                42
#define __SYS_accept                 43
#define __SYS_sendto                 44
#define __SYS_recvfrom               45
#define __SYS_sendmsg                46
#define __SYS_recvmsg                47
#define __SYS_shutdown               48
#define __SYS_bind                   49
#define __SYS_listen                 50
#define __SYS_getsockname            51
#define __SYS_getpeername            52
#define __SYS_socketpair             53
#define __SYS_setsockopt             54
#define __SYS_getsockopt             55
#define __SYS_clone                  56
#define __SYS_fork                   57
#define __SYS_vfork                  58
#define __SYS_execve                 59
#define __SYS_exit                   60
#define __SYS_wait4                  61
#define __SYS_kill                   62
#define __SYS_uname                  63
#define __SYS_semget                 64
#define __SYS_semop                  65
#define __SYS_semctl                 66
#define __SYS_shmdt                  67
#define __SYS_msgget                 68
#define __SYS_msgsnd                 69
#define __SYS_msgrcv                 70
#define __SYS_msgctl                 71
#define __SYS_fcntl                  72
#define __SYS_flock                  73
#define __SYS_fsync                  74
#define __SYS_fdatasync              75
#define __SYS_truncate               76
#define __SYS_ftruncate              77
#define __SYS_getdents               78
#define __SYS_getcwd                 79
#define __SYS_chdir                  80
#define __SYS_fchdir                 81
#define __SYS_rename                 82
#define __SYS_mkdir                  83
#define __SYS_rmdir                  84
#define __SYS_creat                  85
#define __SYS_link                   86
#define __SYS_unlink                 87
#define __SYS_symlink                88
#define __SYS_readlink               89
#define __SYS_chmod                  90
#define __SYS_fchmod                 91
#define __SYS_chown                  92
#define __SYS_fchown                 93
#define __SYS_lchown                 94
#define __SYS_umask                  95
#define __SYS_gettimeofday           96
#define __SYS_getrlimit              97
#define __SYS_getrusage              98
#define __SYS_sysinfo                99
#define __SYS_times                 100
#define __SYS_ptrace                101
#define __SYS_getuid                102
#define __SYS_syslog                103
#define __SYS_getgid                104
#define __SYS_setuid                105
#define __SYS_setgid                106
#define __SYS_geteuid               107
#define __SYS_getegid               108
#define __SYS_setpgid               109
#define __SYS_getppid               110
#define __SYS_getpgrp               111
#define __SYS_setsid                112
#define __SYS_setreuid              113
#define __SYS_setregid              114
#define __SYS_getgroups             115
#define __SYS_setgroups             116
#define __SYS_setresuid             117
#define __SYS_getresuid             118
#define __SYS_setresgid             119
#define __SYS_getresgid             120
#define __SYS_getpgid               121
#define __SYS_setfsuid              122
#define __SYS_setfsgid              123
#define __SYS_getsid                124
#define __SYS_capget                125
#define __SYS_capset                126
#define __SYS_rt_sigpending         127
#define __SYS_rt_sigtimedwait       128
#define __SYS_rt_sigqueueinfo       129
#define __SYS_rt_sigsuspend         130
#define __SYS_sigaltstack           131
#define __SYS_utime                 132
#define __SYS_mknod                 133
#define __SYS_uselib                134
#define __SYS_personality           135
#define __SYS_ustat                 136
#define __SYS_statfs                137
#define __SYS_fstatfs               138
#define __SYS_sysfs                 139
#define __SYS_getpriority           140
#define __SYS_setpriority           141
#define __SYS_sched_setparam        142
#define __SYS_sched_getparam        143
#define __SYS_sched_setscheduler    144
#define __SYS_sched_getscheduler    145
#define __SYS_sched_get_priority_max 146
#define __SYS_sched_get_priority_min 147
#define __SYS_sched_rr_get_interval 148
#define __SYS_mlock                 149
#define __SYS_munlock               150
#define __SYS_mlockall              151
#define __SYS_munlockall            152
#define __SYS_vhangup               153
#define __SYS_modify_ldt            154
#define __SYS_pivot_root            155
#define __SYS__sysctl               156
#define __SYS_prctl                 157
#define __SYS_arch_prctl            158
#define __SYS_adjtimex              159
#define __SYS_setrlimit             160
#define __SYS_chroot                161
#define __SYS_sync                  162
#define __SYS_acct                  163
#define __SYS_settimeofday          164
#define __SYS_mount                 165
#define __SYS_umount2               166
#define __SYS_swapon                167
#define __SYS_swapoff               168
#define __SYS_reboot                169
#define __SYS_sethostname           170
#define __SYS_setdomainname         171
#define __SYS_iopl                  172
#define __SYS_ioperm                173
#define __SYS_create_module         174
#define __SYS_init_module           175
#define __SYS_delete_module         176
#define __SYS_get_kernel_syms       177
#define __SYS_query_module          178
#define __SYS_quotactl              179
#define __SYS_nfsservctl            180
#define __SYS_getpmsg               181
#define __SYS_putpmsg               182
#define __SYS_afs_syscall           183
#define __SYS_tuxcall               184
#define __SYS_security              185
#define __SYS_gettid                186
#define __SYS_readahead             187
#define __SYS_setxattr              188
#define __SYS_lsetxattr             189
#define __SYS_fsetxattr             190
#define __SYS_getxattr              191
#define __SYS_lgetxattr             192
#define __SYS_fgetxattr             193
#define __SYS_listxattr             194
#define __SYS_llistxattr            195
#define __SYS_flistxattr            196
#define __SYS_removexattr           197
#define __SYS_lremovexattr          198
#define __SYS_fremovexattr          199
#define __SYS_tkill                 200
#define __SYS_time                  201
#define __SYS_futex                 202
#define __SYS_sched_setaffinity     203
#define __SYS_sched_getaffinity     204
#define __SYS_set_thread_area       205
#define __SYS_io_setup              206
#define __SYS_io_destroy            207
#define __SYS_io_getevents          208
#define __SYS_io_submit             209
#define __SYS_io_cancel             210
#define __SYS_get_thread_area       211
#define __SYS_lookup_dcookie        212
#define __SYS_epoll_create          213
#define __SYS_epoll_ctl_old         214
#define __SYS_epoll_wait_old        215
#define __SYS_remap_file_pages      216
#define __SYS_getdents64            217
#define __SYS_set_tid_address       218
#define __SYS_restart_syscall       219
#define __SYS_semtimedop            220
#define __SYS_fadvise64             221
#define __SYS_timer_create          222
#define __SYS_timer_settime         223
#define __SYS_timer_gettime         224
#define __SYS_timer_getoverrun      225
#define __SYS_timer_delete          226
#define __SYS_clock_settime         227
#define __SYS_clock_gettime         228
#define __SYS_clock_getres          229
#define __SYS_clock_nanosleep       230
#define __SYS_exit_group            231
#define __SYS_epoll_wait            232
#define __SYS_epoll_ctl             233
#define __SYS_tgkill                234
#define __SYS_utimes                235
#define __SYS_vserver               236
#define __SYS_mbind                 237
#define __SYS_set_mempolicy         238
#define __SYS_get_mempolicy         239
#define __SYS_mq_open               240
#define __SYS_mq_unlink             241
#define __SYS_mq_timedsend          242
#define __SYS_mq_timedreceive       243
#define __SYS_mq_notify             244
#define __SYS_mq_getsetattr         245
#define __SYS_kexec_load            246
#define __SYS_waitid                247
#define __SYS_add_key               248
#define __SYS_request_key           249
#define __SYS_keyctl                250
#define __SYS_ioprio_set            251
#define __SYS_ioprio_get            252
#define __SYS_inotify_init          253
#define __SYS_inotify_add_watch     254
#define __SYS_inotify_rm_watch      255
#define __SYS_migrate_pages         256
#define __SYS_openat                257
#define __SYS_mkdirat               258
#define __SYS_mknodat               259
#define __SYS_fchownat              260
#define __SYS_futimesat             261
#define __SYS_newfstatat            262
#define __SYS_unlinkat              263
#define __SYS_renameat              264
#define __SYS_linkat                265
#define __SYS_symlinkat             266
#define __SYS_readlinkat            267
#define __SYS_fchmodat              268
#define __SYS_faccessat             269
#define __SYS_pselect6              270
#define __SYS_ppoll                 271
#define __SYS_unshare               272
#define __SYS_set_robust_list       273
#define __SYS_get_robust_list       274
#define __SYS_splice                275
#define __SYS_tee                   276
#define __SYS_sync_file_range       277
#define __SYS_vmsplice              278
#define __SYS_move_pages            279
#define __SYS_utimensat             280
#define __SYS_epoll_pwait           281
#define __SYS_signalfd              282
#define __SYS_timerfd_create        283
#define __SYS_eventfd               284
#define __SYS_fallocate             285
#define __SYS_timerfd_settime       286
#define __SYS_timerfd_gettime       287
#define __SYS_accept4               288
#define __SYS_signalfd4             289
#define __SYS_eventfd2              290
#define __SYS_epoll_create1         291
#define __SYS_dup3                  292
#define __SYS_pipe2                 293
#define __SYS_inotify_init1         294
#define __SYS_preadv                295
#define __SYS_pwritev               296
#define __SYS_rt_tgsigqueueinfo     297
#define __SYS_perf_event_open       298
#define __SYS_recvmmsg              299
#define __SYS_fanotify_init         300
#define __SYS_fanotify_mark         301
#define __SYS_prlimit64             302
#define __SYS_name_to_handle_at     303
#define __SYS_open_by_handle_at     304
#define __SYS_clock_adjtime         305
#define __SYS_syncfs                306
#define __SYS_sendmmsg              307
#define __SYS_setns                 308
#define __SYS_getcpu                309
#define __SYS_process_vm_readv      310
#define __SYS_process_vm_writev     311
#define __SYS_kcmp                  312
#define __SYS_finit_module          313
#define __SYS_sched_setattr         314
#define __SYS_sched_getattr         315
#define __SYS_renameat2             316
#define __SYS_seccomp               317
#define __SYS_getrandom             318
#define __SYS_memfd_create          319
#define __SYS_kexec_file_load       320
#define __SYS_bpf                   321
#define __SYS_execveat              322
#define __SYS_userfaultfd           323
#define __SYS_membarrier            324
#define __SYS_mlock2                325
#define __SYS_copy_file_range       326
#define __SYS_preadv2               327
#define __SYS_pwritev2              328
#define __SYS_pkey_mprotect         329
#define __SYS_pkey_alloc            330
#define __SYS_pkey_free             331
#define __SYS_statx                 332
#define __SYS_io_pgetevents         333
#define __SYS_rseq                  334
#define __SYS_pidfd_send_signal     424
#define __SYS_io_uring_setup        425
#define __SYS_io_uring_enter        426
#define __SYS_io_uring_register     427
#define __SYS_open_tree             428
#define __SYS_move_mount            429
#define __SYS_fsopen                430
#define __SYS_fsconfig              431
#define __SYS_fsmount               432
#define __SYS_fspick                433
#define __SYS_pidfd_open            434
#define __SYS_clone3                435
#define __SYS_close_range           436
#define __SYS_openat2               437
#define __SYS_pidfd_getfd           438
#define __SYS_faccessat2            439
#define __SYS_process_madvise       440

#endif /* __LIBC_LINUX_X86_64_BITS_SYSCALL_TABLE_H__ */
