#ifndef __SYSCALL_TABLE_H__
#define __SYSCALL_TABLE_H__

#define __SYS_io_setup            0
#define __SYS_io_destroy          1
#define __SYS_io_submit           2
#define __SYS_io_cancel           3
#define __SYS_io_getevents        4
#define __SYS_setxattr            5
#define __SYS_lsetxattr           6
#define __SYS_fsetxattr           7
#define __SYS_getxattr            8
#define __SYS_lgetxattr           9
#define __SYS_fgetxattr           10
#define __SYS_listxattr           11
#define __SYS_llistxattr          12
#define __SYS_flistxattr          13
#define __SYS_removexattr         14
#define __SYS_lremovexattr        15
#define __SYS_fremovexattr        16
#define __SYS_getcwd              17
#define __SYS_lookup_dcookie      18
#define __SYS_eventfd2            19
#define __SYS_epoll_create1       20
#define __SYS_epoll_ctl           21
#define __SYS_epoll_pwait         22
#define __SYS_dup                 23
#define __SYS_dup3                24
#define __SYS_fcntl               25
#define __SYS_inotify_init1       26
#define __SYS_inotify_add_watch   27
#define __SYS_inotify_rm_watch    28
#define __SYS_ioctl               29
#define __SYS_ioprio_set          30
#define __SYS_ioprio_get          31
#define __SYS_flock               32
#define __SYS_mknodat             33
#define __SYS_mkdirat             34
#define __SYS_unlinkat            35
#define __SYS_symlinkat           36
#define __SYS_linkat              37
#define __SYS_renameat            38
#define __SYS_umount2             39
#define __SYS_mount               40
#define __SYS_pivot_root          41
#define __SYS_nfsservctl          42
#define __SYS_statfs              43
#define __SYS_fstatfs             44
#define __SYS_truncate            45
#define __SYS_ftruncate           46
#define __SYS_fallocate           47
#define __SYS_faccessat           48
#define __SYS_chdir               49
#define __SYS_fchdir              50
#define __SYS_chroot              51
#define __SYS_fchmod              52
#define __SYS_fchmodat            53
#define __SYS_fchownat            54
#define __SYS_fchown              55
#define __SYS_openat              56
#define __SYS_close               57
#define __SYS_vhangup             58
#define __SYS_pipe2               59
#define __SYS_quotactl            60
#define __SYS_getdents64          61
#define __SYS_lseek               62
#define __SYS_read                63
#define __SYS_write               64
#define __SYS_readv               65
#define __SYS_writev              66
#define __SYS_pread64             67
#define __SYS_pwrite64            68
#define __SYS_preadv              69
#define __SYS_pwritev             70
#define __SYS_sendfile            71
#define __SYS_pselect6            72
#define __SYS_ppoll               73
#define __SYS_signalfd4           74
#define __SYS_vmsplice            75
#define __SYS_splice              76
#define __SYS_tee                 77
#define __SYS_readlinkat          78
#define __SYS_newfstatat          79
#define __SYS_fstat               80
#define __SYS_sync                81
#define __SYS_fsync               82
#define __SYS_fdatasync           83
#define __SYS_sync_file_range     84
#define __SYS_timerfd_create      85
#define __SYS_timerfd_settime     86
#define __SYS_timerfd_gettime     87
#define __SYS_utimensat           88
#define __SYS_acct                89
#define __SYS_capget              90
#define __SYS_capset              91
#define __SYS_personality         92
#define __SYS_exit                93
#define __SYS_exit_group          94
#define __SYS_waitid              95
#define __SYS_set_tid_address     96
#define __SYS_unshare             97
#define __SYS_futex               98
#define __SYS_set_robust_list     99
#define __SYS_get_robust_list     100
#define __SYS_nanosleep           101
#define __SYS_getitimer           102
#define __SYS_setitimer           103
#define __SYS_kexec_load          104
#define __SYS_init_module         105
#define __SYS_delete_module       106
#define __SYS_timer_create        107
#define __SYS_timer_gettime       108
#define __SYS_timer_getoverrun    109
#define __SYS_timer_settime       110
#define __SYS_timer_delete        111
#define __SYS_clock_settime       112
#define __SYS_clock_gettime       113
#define __SYS_clock_getres        114
#define __SYS_clock_nanosleep     115
#define __SYS_syslog              116
#define __SYS_ptrace              117
#define __SYS_sched_setparam      118
#define __SYS_sched_setscheduler  119
#define __SYS_sched_getscheduler  120
#define __SYS_sched_getparam      121
#define __SYS_sched_setaffinity   122
#define __SYS_sched_getaffinity   123
#define __SYS_sched_yield         124
#define __SYS_sched_get_priority_max 125
#define __SYS_sched_get_priority_min 126
#define __SYS_sched_rr_get_interval 127
#define __SYS_restart_syscall     128
#define __SYS_kill                129
#define __SYS_tkill               130
#define __SYS_tgkill              131
#define __SYS_sigaltstack         132
#define __SYS_rt_sigsuspend       133
#define __SYS_rt_sigaction        134
#define __SYS_rt_sigprocmask      135
#define __SYS_rt_sigpending       136
#define __SYS_rt_sigtimedwait     137
#define __SYS_rt_sigqueueinfo     138
#define __SYS_rt_sigreturn        139
#define __SYS_setpriority         140
#define __SYS_getpriority         141
#define __SYS_reboot              142
#define __SYS_setregid            143
#define __SYS_setgid              144
#define __SYS_setreuid            145
#define __SYS_setuid              146
#define __SYS_setresuid           147
#define __SYS_getresuid           148
#define __SYS_setresgid           149
#define __SYS_getresgid           150
#define __SYS_setfsuid            151
#define __SYS_setfsgid            152
#define __SYS_times               153
#define __SYS_setpgid             154
#define __SYS_getpgid             155
#define __SYS_getsid              156
#define __SYS_setsid              157
#define __SYS_getgroups           158
#define __SYS_setgroups           159
#define __SYS_uname               160
#define __SYS_sethostname         161
#define __SYS_setdomainname       162
#define __SYS_getrlimit           163
#define __SYS_setrlimit           164
#define __SYS_getrusage           165
#define __SYS_umask               166
#define __SYS_prctl               167
#define __SYS_getcpu              168
#define __SYS_gettimeofday        169
#define __SYS_settimeofday        170
#define __SYS_adjtimex            171
#define __SYS_getpid              172
#define __SYS_getppid             173
#define __SYS_getuid              174
#define __SYS_geteuid             175
#define __SYS_getgid              176
#define __SYS_getegid             177
#define __SYS_gettid              178
#define __SYS_sysinfo             179
#define __SYS_mq_open             180
#define __SYS_mq_unlink           181
#define __SYS_mq_timedsend        182
#define __SYS_mq_timedreceive     183
#define __SYS_mq_notify           184
#define __SYS_mq_getsetattr       185
#define __SYS_msgget              186
#define __SYS_msgctl              187
#define __SYS_msgrcv              188
#define __SYS_msgsnd              189
#define __SYS_semget              190
#define __SYS_semctl              191
#define __SYS_semtimedop          192
#define __SYS_semop               193
#define __SYS_shmget              194
#define __SYS_shmctl              195
#define __SYS_shmat               196
#define __SYS_shmdt               197
#define __SYS_socket              198
#define __SYS_socketpair          199
#define __SYS_bind                200
#define __SYS_listen              201
#define __SYS_accept              202
#define __SYS_connect             203
#define __SYS_getsockname         204
#define __SYS_getpeername         205
#define __SYS_sendto              206
#define __SYS_recvfrom            207
#define __SYS_setsockopt          208
#define __SYS_getsockopt          209
#define __SYS_shutdown            210
#define __SYS_sendmsg             211
#define __SYS_recvmsg             212
#define __SYS_readahead           213
#define __SYS_brk                 214
#define __SYS_munmap              215
#define __SYS_mremap              216
#define __SYS_add_key             217
#define __SYS_request_key         218
#define __SYS_keyctl              219
#define __SYS_clone               220
#define __SYS_execve              221
#define __SYS_mmap                222
#define __SYS_fadvise64           223
#define __SYS_swapon              224
#define __SYS_swapoff             225
#define __SYS_mprotect            226
#define __SYS_msync               227
#define __SYS_mlock               228
#define __SYS_munlock             229
#define __SYS_mlockall            230
#define __SYS_munlockall           231
#define __SYS_mincore              232
#define __SYS_madvise              233
#define __SYS_remap_file_pages      234
#define __SYS_mbind                235
#define __SYS_get_mempolicy        236
#define __SYS_set_mempolicy        237
#define __SYS_migrate_pages        238
#define __SYS_move_pages           239
#define __SYS_rt_tgsigqueueinfo    240
#define __SYS_perf_event_open      241
#define __SYS_accept4              242
#define __SYS_recvmmsg             243
#define __SYS_wait4                260
#define __SYS_prlimit64            261
#define __SYS_fanotify_init        262
#define __SYS_fanotify_mark        263
#define __SYS_name_to_handle_at    264
#define __SYS_open_by_handle_at    265
#define __SYS_clock_adjtime        266
#define __SYS_syncfs               267
#define __SYS_setns                268
#define __SYS_sendmmsg             269
#define __SYS_process_vm_readv     270
#define __SYS_process_vm_writev    271
#define __SYS_kcmp                 272
#define __SYS_finit_module         273
#define __SYS_sched_setattr        274
#define __SYS_sched_getattr        275
#define __SYS_renameat2            276
#define __SYS_seccomp              277
#define __SYS_getrandom            278
#define __SYS_memfd_create         279
#define __SYS_bpf                  280
#define __SYS_execveat             281
#define __SYS_userfaultfd          282
#define __SYS_membarrier           283
#define __SYS_mlock2               284
#define __SYS_copy_file_range      285
#define __SYS_preadv2              286
#define __SYS_pwritev2             287
#define __SYS_pkey_mprotect        288
#define __SYS_pkey_alloc           289
#define __SYS_pkey_free            290
#define __SYS_statx                291
#define __SYS_io_uring_setup       425
#define __SYS_io_uring_enter       426
#define __SYS_faccessat2           439

#endif /* __SYSCALL_TABLE_H__ */
